### ISSUE TITLE
[DatePicker]: styles are off when passing the option `inline: true` in flatpickrOptions

### ISSUE THREAD

**Issue by AlexandraMadalina** [carbon-design-system/carbon-components-angular#2761]
## Detailed description

Hi. I'm using the carbon date picker and I need it to be always open. I see that carbon is using flatpickr that can be configured with inline: true  to achieve that but the styles go off. The input is on the left side of the calendar, and the calendar icon that was supposed to be in the input is on the calendar.
i'm using  carbon-components-angular: 5.14.0

`
   <cds-date-picker
                    size="sm"
                    [flatpickrOptions]="{  inline: true }"
     ></cds-date-picker>
`

<img width="610" alt="Screenshot 2024-01-18 at 12 55 18" src="https://github.com/carbon-design-system/carbon-components-angular/assets/47785112/d3822b83-f5c2-460f-91b5-6a6653bccf1d">

**Comment by Akshat55** [comment]
That's expected, we don't support all functionalities of flatpickr out of the box. This is caused by conflicting styles set by carbon and flatpickr.


You can paste the following code snippet in your component to fix this. Keep in mind that this may need to adjust styling based on your usage.

```css
:host {
  :ng-deep {
    .cds--date-picker-input__wrapper {
       flex-direction: column; // It is row out of the box.
    }
    
    // Update the alignment of the icon.
    .cds--date-picker__icon {
      right: 2rem;
      top: 2.5rem;
    }
  }
}

```

Remember to ensure your styles do not leak since I'm using `ng-deep` here. It should be wrapped in `:host` so the styles do not leak outside of the component.

Closing the issue, feel free to reopen or comment!
